# fastyumjin override for existing HinLink HT2 board
source "${SRC}/config/boards/hinlink-ht2.csc"
BOARD_NAME="HinLink HT2 (fastyumjin)"
BOOT_FDT_FILE="rockchip/rk3528-hinlink-h28k.dtb"
BOOTCONFIG="hinlink_rk3528_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
