# fastyumjin override for existing HinLink HT2 board
source "${SRC}/config/boards/hinlink-ht2.csc"
BOARD_NAME="HinLink HT2 (fastyumjin)"
BOARD_VENDOR="hinlink"
BOARDFAMILY="rk35xx"
BOOT_SOC="rk3528"
BOOTCONFIG="hinlink_rk3528_defconfig"
BOOT_FDT_FILE="fastyumjin.dtb"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
